### ISSUE TITLE
Any plans for affine transformation matrixes?

### ISSUE THREAD

**Issue by mbylstra** [opensolid/geometry#14]
This library looks really great - awesome features and superb documentation. 

There's one thing I can't seem to find though - matrix transformations (for affine transformations). I like how rotateBy, translateBy, etc is really intuitive and doesn't require a deep understanding of linear algebra, but I'm porting some geographic JS code that just has a hardcoded 3x3 transformation matrix. I have no idea what it is doing (translating, scaling or rotating) as my linear algebra is extremely rusty. What I'd like is a function like http://package.elm-lang.org/packages/elm-community/linear-algebra/1.2.1/Math-Matrix4#transform but for 2D as well as 3D. From memory stacking linear tranformations and then applying the resulting matrix to a point is also potentially faster than applying transforms to points one at a time, but I could be wrong about that. Perhaps matrix transforms could be added as an advanced feature?

**Comment by mbylstra** [comment]
As an aside, according to the issues, elm-community/linear-algebra does not have any plans to support 2D transforms, as it really just a legacy package that supports the webGL package. (I think it should be renamed linear-algebra-3d). I would support this package become the official "blessed" geometry/linear-algebra library. There are quite a few of them in elm-package, so it's hard to choose.

**Comment by ianmackenzie** [comment]
Thanks for the kind words Michael! This is exactly the sort of question I expected to come up once people started taking a careful look at the package, so congratulations on being the first =) There are several different answers here, so this will be a longish reply...

The first answer is that many uses of transformation matrices can be replaced with a `Frame2d` or `Frame3d` and then use of the various `placeIn` functions. If you happen to know that your 2D transformation matrix represents a rigid transformation (rotation and translation only, no scaling or shear), then a transformation matrix

```
[ a c e ]
[ b d f ]
[ 0 0 1 ]
```

can be represented as

```elm
frame =
    Frame2d
        { xDirection = Direction2d ( a, b )
        , yDirection = Direction2d ( c, d )
        , originPoint = Point2d ( e, f )
        }
```

and a hypothetical `Point2d.transformedBy matrix point` can be implemented as `Point2d.placeIn frame point`. (Mathematically, this works because any rigid transformation can be represented as a [change of basis](http://www.michaelkeutel.de/blog/rotation-matrices-vector-basis/).)

You can also use a `Frame2d`/`Frame3d` to address the (completely valid) efficiency concerns you mentioned - for example, if you construct a `Point2d` transformation function

```elm
transformation : Point2d -> Point2d
transformation =
    Point2d.rotateAround Point2d.origin (degrees 45)
        >> Point2d.mirrorAcross Axis2d.y
        >> Point2d.translateBy (Vector2d ( 2, 3 ))
```

then yes, it will be less efficient than using a single transformation matrix (although there are some optimizations so that, for example, the sines and cosines involved in rotation will only be evaluated once when the function is constructed and not every time it's called). If you want a more efficient 'baked' version of the same transformation, you can instead do

```elm
frame : Frame2d
frame =
    Frame2d.xy
        |> Frame2d.rotateAround Point2d.origin (degrees 45)
        |> Frame2d.mirrorAcross Axis2d.y
        |> Frame2d.translateBy (Vector2d ( 2, 3 ))

transformation : Point2d -> Point2d
transformation =
    Point2d.placeIn frame
```

I wanted to avoid transformation matrices as much as possible, since I find them confusing and error-prone - I like the fact that unlike a matrix which is an abstract mathematical concept, a `Frame3d` can be visualized as an actual 'thing' like a little styrofoam ball with toothpicks sticking out of it, which you can translate and rotate around. I was worried that if I included a `TransformationMatrix2d` type and then had `Point2d.transformedBy` etc. functions, people would see that and think "yeah, transformation matrices, that's what I want" whereas I think in most cases the more explicit functions are much clearer.

That said, now that I think about it, how about functions like:

```elm
Point2d.affineTransformation: Float -> Float -> Float -> Float -> Float -> Float -> Point2d -> Point2d
```

or perhaps

```elm
Point2d.affineTransformation: ( Float, Float, Float, Float, Float, Float ) -> Point2d -> Point2d
```

The 'mathy' names and ugly type signatures would be a pretty strong hint that these are for low-level, high-performance use, and they wouldn't require adding any new `TransformationMatrix2d` etc. types.

Note that `affineTransformation` could be implemented for `Point2d`, `Point3d`, `Triangle2d`, `Triangle3d` etc. but not for types like `Direction2d`, `Direction3d`, `Frame2d`, `Frame3d` since a general affine transformation matrix might apply scaling (invalid for a direction, since it must have a magnitude of one) or shear (invalid for frames since their basis directions must remain mutually perpendicular).

Whew - I think that's long enough for one reply, so I'll reply separately to your second comment...

**Comment by ianmackenzie** [comment]
As for your second commend, there were some discussions about this on the #webgl channel on Elm Slack recently. My personal preference would be for [`zinggi/elm-webgl-math`](http://package.elm-lang.org/packages/Zinggi/elm-webgl-math/latest) to be the 'standard' library that everyone provided converters to and from; I like that it uses plain tuples as its data representation so you could actually support converting to and from its types without having a dependency on the package if you wanted to! However, the author of that package pointed out that there are several different valid representations of (for example) a 2D vector - a tuple, a record, or a union type (which could contain a tuple, a record, or separate fields...) and it might not make sense to force everyone into a particular one.

As much as I would like `opensolid/geometry` to be used by as many people as possible, it's probably too heavy to be 'the official' package - specifically, I don't think it would make sense for `elm-community/webgl` to depend on something as big as `opensolid/geometry` for the types allowed in meshes/shaders. And though it would be nice for there to be one standard, it doesn't really seem so bad to do a few tuple-based conversions here and there. For example, you could pass the result of `Vector3d.components vector` directly to any of the functions in `zinggi/elm-webgl-math`'s [`Vector3`](http://package.elm-lang.org/packages/Zinggi/elm-webgl-math/latest/Vector3) module...

I guess what it comes down to is that I'm happy to support some sort of standardization effort and provide converters to and from a standard package (or perhaps even have this package be internally based on a standard lower-level package), but it's not something I'm currently pushing hard for.

**Comment by mbylstra** [comment]
Thanks for the detailed response, and the instructions on how to convert a transformation matrix into a Frame2D were very informative. I agree that functions like `mirrorAcross`, `translateBy` and `rotateAround` are far more intuitive than affine transformation matrixes. I'll leave it to you to decide whether to include an affineTransformation function for advanced use cases. Feel free to close the issue if you decide against it.

**Comment by ianmackenzie** [comment]
For now I've decided to address this by publishing [`opensolid/linear-algebra`](http://package.elm-lang.org/packages/opensolid/linear-algebra/latest) and [`opensolid/webgl-math`](http://package.elm-lang.org/packages/opensolid/webgl-math/latest) to provide nice interop with a couple of the more popular linear algebra packages. The interop packages allow you to write things like `Point3d.transformBy matrix point` where `matrix` is a `linear-algebra` or `elm-webgl-math` matrix and `point` is an OpenSolid `Point3d` (see more examples in the docs for each package).

This doesn't fully address the issue of 2D affine transformations specifically, as neither of those packages has comprehensive support for 2D transforms yet, but hopefully over time that will improve (perhaps through some pull requests? =)). In the meantime you can use `elm-webgl-math` and just construct matrices yourself, since its 2D matrix types are just tuples of tuples - there are [some](http://package.elm-lang.org/packages/opensolid/webgl-math/1.0.0/OpenSolid-WebGLMath-Point2d#transformBy) [examples](http://package.elm-lang.org/packages/opensolid/webgl-math/1.0.0/OpenSolid-WebGLMath-Vector2d#transformBy) of this in the `opensolid/webgl-math` docs.
