### ISSUE TITLE
Problems importing `OpenSolid.Rectangle2d`

### ISSUE THREAD

**Issue by architectcodes** [opensolid/geometry#42]
Hey, since 2.1.0 I have a weird problem importing `OpenSolid.Rectangle2d`. It can be reproduced by visiting https://ellie-app.com/qnhLYgjy8a1/1 and editing the line
```elm
import OpenSolid.Arc2d
```
so it reads
```elm
import OpenSolid.Rectangle2d
```
and trying to compile. Ellie wouldn’t let me save or share the project with the latter in it 🤷‍♂️

This is also happening locally in my project. I didn’t notice any other weird un-importable modules like this 🙂

**Comment by ianmackenzie** [comment]
Is this perhaps because you were previously using `opensolid/geometry` via an entry in `source-directories` instead of as an installed package? The `Rectangle2d` module has never actually been exposed, primarily since I haven't gotten around to documenting it. Assuming that's the case, I'll take this as a reminder to finish documenting the `Rectangle2d` module so it *can* be exposed =)

**Comment by architectcodes** [comment]
Ahhh okay, it was just that – all clear now!

The reason why the error cropped up just now is that the `Rectangle2d` was used by a yet-unreleased package in my `source-directories`, `opensolid/parametric`. An update of a proper and law abiding dependency `opensolid/linear-algebra-interop` brought `opensolid/geometry` along with it, so I needed to move it away from `source-directories`. That’s where the error cropped up!

Sorry for the false alarm 😇
